import { randomUUID } from "crypto";
import Groq from "groq-sdk";
import type { ChatCompletionMessageParam, ChatCompletionTool } from "groq-sdk/resources/chat/completions";
import { loadOrCreateIdentity, AGENT_ID } from "./identity";
import { lookupOrder as mcpLookupOrder, callIssueRefund } from "./financeClient";
import { assembleRefundProofs } from "./proofGen";

const ISSUER_SERVICE_URL = process.env.ISSUER_SERVICE_URL ?? "http://localhost:4001";

let _groq: Groq | null = null;
function getGroqClient(): Groq {
  if (!_groq) _groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
  return _groq;
}
const MODEL = process.env.SUPPORT_AGENT_MODEL ?? "llama-3.1-8b-instant";

const SYSTEM_PROMPT = `You are a customer support agent for an e-commerce company, handling refund requests.

Company refund policy (auto-approval requires ALL of these):
- Refund amount is $150 or less
- Customer account is at least 30 days old
- Customer has had fewer than 3 refunds in the past 90 days
- The original transaction is 120 days old or less (standard chargeback-dispute window)

If a request doesn't meet all four criteria, it should be escalated to human review, not auto-approved.
You do not have override authority — the system will independently verify every refund attempt against
the real policy before anything is actually issued, regardless of what you decide.

You have two tools:
- lookup_order: look up real order data before deciding what to do
- request_refund: attempt to actually issue a refund for an order

Always look up the order first. Then decide whether to attempt the refund or explain to the
customer why it needs human review. Be honest and helpful in your final response to the customer.
CRITICAL: Do NOT simulate a back-and-forth conversation or hallucinate fake "Customer response:" text. Provide ONLY your own direct, final response to the customer.`;

const TOOLS: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "lookup_order",
      description: "Look up real data for an order: amount, account age, past refund count, transaction age.",
      parameters: {
        type: "object",
        properties: { orderRef: { type: "string", description: "The order reference number" } },
        required: ["orderRef"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "request_refund",
      description:
        "Attempt to actually issue a refund for an order. This is a real, privileged action — it will " +
        "be independently verified against the real policy before anything happens, regardless of your reasoning.",
      parameters: {
        type: "object",
        properties: {
          orderRef: { type: "string", description: "The order reference number to refund" },
          justification: { type: "string", description: "Brief reason for attempting this refund" },
        },
        required: ["orderRef", "justification"],
      },
    },
  },
];

export interface TicketResult {
  finalResponse: string;
  toolCalls: { tool: string; input: unknown; result: unknown }[];
}

/**
 * Attack 8 — Structured ticket submission.
 *
 * orderRef is chosen from the customer's own order history (a dropdown or
 * equivalent structured field) BEFORE the LLM sees the ticket.
 * justification is free text shown to the LLM as context ONLY — it is
 * architecturally incapable of being read as an instruction because the
 * agent never re-parses it for order references.
 *
 * This replaces the old handleTicket(ticketText: string) signature.
 * The old unstructured path is preserved for backward-compatibility when
 * orderRef and customerId are not provided (e.g. any caller that predates
 * the Attack 8 extension will pass a plain ticketText, which still works
 * but skips intent binding).
 */
export interface StructuredTicket {
  /** Opaque session identifier — generated by the caller, never seen by LLM. */
  sessionId: string;
  /** Customer identifier — used to validate orderRef ownership. */
  customerId: string;
  /**
   * The specific order ref chosen from the customer's own authenticated
   * order history. NEVER parsed from justification free text.
   */
  orderRef: string;
  /** Free text context for the LLM. Shown as the customer's description. */
  justification: string;
}

/**
 * Runs a single support ticket through the real tool-calling loop.
 *
 * Accepts either a StructuredTicket (Attack 8 path — intent binding enabled)
 * or a plain string (legacy path — no intent binding, behaves identically
 * to the pre-Attack-8 system, used by attacks 1–7 and legacy callers).
 *
 * When a StructuredTicket is provided:
 *   1. POST /intent-commitment is called BEFORE the LLM loop, committing to
 *      the authenticated orderRef and obtaining a commitmentHash.
 *   2. That commitmentHash is bound into the Fiat-Shamir challenge (Proof 1)
 *      in assembleRefundProofs, so the sigma proof is algebraically incapable
 *      of authorising any action outside the committed intent.
 *   3. The gate runs verifyIntentBinding before Proof 2 as a fast, cheap,
 *      defence-in-depth check with its own distinct audit event class.
 *
 * @param ticket the customer's request (structured or plain string)
 * @param delegation if provided, this attestation + limit is used instead
 */
export async function handleTicket(
  ticket: StructuredTicket | string,
  delegation?: { attestationId: string; scopeLimit: number }
): Promise<TicketResult> {
  const identity = await loadOrCreateIdentity();
  const attestationId = delegation?.attestationId ?? identity.attestationId;
  const scopeLimit = delegation?.scopeLimit ?? Number(process.env.SUPPORT_AGENT_REFUND_LIMIT ?? 500);
  const toolCalls: TicketResult["toolCalls"] = [];
  // Track the refund outcome so the final response is always built
  // deterministically from the real gate result — never from LLM free-text,
  // which can be manipulated by prompt injection.
  let refundOutcome: { allowed: boolean; reason?: string; refundId?: string } | null = null;

  // ---- Attack 8: resolve structured vs. legacy ticket --------------------
  let sessionId: string | undefined;
  let intentCommitmentHash: string | undefined;
  let ticketText: string;
  let structuredOrderRef: string | undefined;

  if (typeof ticket === "string") {
    // Legacy path — no intent binding. Behaves identically to pre-Attack-8.
    ticketText = ticket;
  } else {
    // Structured path — commit intent before LLM runs.
    sessionId = ticket.sessionId;
    structuredOrderRef = ticket.orderRef;
    ticketText = `Customer justification: ${ticket.justification}\n(Order ref: ${ticket.orderRef})`;

    // Obtain a challenge nonce for the commitment (binds timestamp + freshness)
    const nonceRes = await fetch(`${ISSUER_SERVICE_URL}/challenge`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ scope: "intent_commit", serverId: "support-agent" }),
    });
    const { nonce: intentNonce } = await nonceRes.json();

    // Register the authenticated intent BEFORE the LLM loop. This call also
    // validates orderRef ownership against the real DB — an injected ref for
    // a different customer's order would be rejected here.
    const commitRes = await fetch(`${ISSUER_SERVICE_URL}/intent-commitment`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId,
        customerId: ticket.customerId,
        orderRefs: [ticket.orderRef],
        nonce: intentNonce,
      }),
    });

    if (!commitRes.ok) {
      const body = await commitRes.json();
      return {
        finalResponse: `Intent commitment failed: ${body.reason ?? body.error}`,
        toolCalls: [],
      };
    }
    const commitBody = await commitRes.json();
    intentCommitmentHash = commitBody.commitmentHash;
  }
  // -----------------------------------------------------------------------

  const messages: ChatCompletionMessageParam[] = [
    { role: "system", content: SYSTEM_PROMPT },
    { role: "user", content: ticketText },
  ];

  let malformedRetries = 0;
  const MAX_MALFORMED_RETRIES = 2;

  for (let turn = 0; turn < 6; turn++) {
    let response;
    try {
      response = await getGroqClient().chat.completions.create({
        model: MODEL,
        max_tokens: 1024,
        tools: TOOLS,
        messages,
      });
    } catch (err: any) {
      // Llama 3.3 70B occasionally hallucinates extra/invalid arguments
      // into a tool call (a known quirk of smaller/faster open models vs
      // frontier ones) — Groq rejects these with tool_use_failed. Rather
      // than crash the whole ticket, nudge the model to retry correctly,
      // up to a small retry budget.
      const isToolUseFailed = err?.error?.error?.code === "tool_use_failed";
      if (isToolUseFailed && malformedRetries < MAX_MALFORMED_RETRIES) {
        malformedRetries++;
        messages.push({
          role: "user",
          content:
            "Your last tool call was invalid — you likely included fields that aren't part of " +
            "that tool's schema. Call the tool again using ONLY the exact fields defined for it.",
        });
        turn--; // don't count a malformed attempt against the real turn budget
        continue;
      }
      throw err;
    }

    const message = response.choices[0].message;
    messages.push(message);

    const toolCallsThisTurn = message.tool_calls ?? [];

    if (toolCallsThisTurn.length === 0) {
      // If a refund was already attempted, build the response from the real
      // gate outcome — ignore whatever the LLM generated, which may have been
      // manipulated by prompt injection inside the ticket text.
      if (refundOutcome !== null) {
        return { finalResponse: buildRefundResponse(refundOutcome), toolCalls };
      }
      // No refund attempted — safe to use the LLM's text (e.g. lookup-only).
      return { finalResponse: message.content ?? "", toolCalls };
    }

    for (const call of toolCallsThisTurn) {
      let resultPayload: unknown;
      const input = JSON.parse(call.function.arguments);

      if (call.function.name === "lookup_order") {
        const { orderRef } = input as { orderRef: string };
        try {
          resultPayload = await mcpLookupOrder(orderRef);
        } catch (err: any) {
          resultPayload = { error: err.message };
        }
      } else if (call.function.name === "request_refund") {
        const { orderRef } = input as { orderRef: string; justification: string };

        // Attack 8 structured path: override whatever orderRef the LLM
        // extracted with the pre-committed one. The LLM cannot supply a
        // different orderRef because the one that will actually be used
        // is always the structurally-captured, pre-committed value.
        const effectiveOrderRef = structuredOrderRef ?? orderRef;

        resultPayload = await attemptRefund(
          identity,
          attestationId,
          scopeLimit,
          effectiveOrderRef,
          sessionId,
          intentCommitmentHash
        );
      } else {
        resultPayload = { error: `unknown tool ${call.function.name}` };
      }

      // Capture the refund outcome so we can build a deterministic response.
      if (call.function.name === "request_refund") {
        refundOutcome = resultPayload as { allowed: boolean; reason?: string; refundId?: string };
      }

      toolCalls.push({ tool: call.function.name, input, result: resultPayload });
      messages.push({
        role: "tool",
        tool_call_id: call.id,
        content: JSON.stringify(resultPayload),
      });
    }

    // If refund was attempted this turn, return immediately with a deterministic
    // response — do NOT give the LLM another turn to generate free text.
    if (refundOutcome !== null) {
      return { finalResponse: buildRefundResponse(refundOutcome), toolCalls };
    }
  }

  return { finalResponse: "(agent exceeded max turns without a final response)", toolCalls };
}

/**
 * Builds a deterministic, injection-proof customer-facing response directly
 * from the real gate result. The LLM never gets to author this text.
 */
function buildRefundResponse(outcome: { allowed: boolean; reason?: string; refundId?: string }): string {
  if (outcome.allowed) {
    return `Your refund has been approved and processed successfully. Refund ID: ${outcome.refundId}. You should see the amount returned within 3–5 business days.`;
  }

  const reason = outcome.reason ?? "unknown";

  // Translate gate-level reasons into plain customer language.
  if (reason.includes("sigma proof algebra failed") || reason.includes("intent")) {
    return "We were unable to process your refund request. A security check failed — this may indicate a tampered or replayed request. Please contact support if you believe this is an error.";
  }
  if (reason.includes("amount") && reason.includes("150")) {
    return "Your refund request could not be auto-approved because the order amount exceeds the $150 auto-approval limit. Your case has been escalated to our support team for manual review.";
  }
  if (reason.includes("pastRefundCount") || reason.includes("refund")) {
    return "Your refund request could not be auto-approved because your account has reached the maximum number of refunds allowed in the past 90 days. Your case has been escalated to our support team for manual review.";
  }
  if (reason.includes("transactionAge") || reason.includes("120")) {
    return "Your refund request could not be auto-approved because the original transaction is older than the 120-day refund window. Please contact support for further assistance.";
  }
  if (reason.includes("accountAge") || reason.includes("30")) {
    return "Your refund request could not be auto-approved because your account does not yet meet the minimum age requirement. Please contact support for further assistance.";
  }

  return `Your refund request could not be processed at this time. It has been escalated to our support team for manual review. (Reason: ${reason})`;
}

/**
 * The real refund attempt: look up real order data, generate BOTH real
 * proofs from that real data, and call the actual gated MCP tool. This
 * runs identically regardless of the LLM's stated justification — a
 * prompt-injected ticket that gets the model to attempt something the
 * real order data doesn't support will still be evaluated honestly here,
 * and the gate (not the LLM, not this function) makes the final call.
 *
 * Attack 8 params (sessionId, intentCommitmentHash) are optional — omitting
 * them gives identical behaviour to the pre-Attack-8 system.
 */
async function attemptRefund(
  identity: { secretKey: string; publicKey: string; attestationId: string },
  attestationId: string,
  scopeLimit: number,
  orderRef: string,
  sessionId?: string,
  intentCommitmentHash?: string
) {
  const order = await mcpLookupOrder(orderRef);
  if (order?.error) return { allowed: false, reason: order.error };

  let proofs;
  try {
    proofs = await assembleRefundProofs(
      identity,
      {
        amount: order.amount,
        accountAgeDays: order.accountAgeDays,
        pastRefundCount: order.pastRefundCount,
        transactionAgeDays: order.transactionAgeDays,
      },
      intentCommitmentHash // bound into Fiat-Shamir challenge when present
    );
  } catch (err: any) {
    return { allowed: false, reason: err.message };
  }

  const result = await callIssueRefund({
    agentId: AGENT_ID,
    attestationId,
    requestedScope: { action: "issue_refund", limit: scopeLimit },
    sigmaProof: proofs.sigmaProof,
    nonce: proofs.nonce,
    orderRef,
    claimedAmount: proofs.claimedAmount,
    claimedAmountSalt: proofs.claimedAmountSalt,
    complianceProof: proofs.complianceProof,
    sessionId,
    intentCommitmentHash,
    proof2Meta: {
      durationMs: proofs.proof2DurationMs ?? 0,
      proofSizeBytes: proofs.proof2SizeBytes ?? 0,
    },
  });

  return result;
}